name: Node CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and test
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Run binary with no args
      run: node ./bin/clj-kondo
      env:
        CI: true
