name: Release sync

on: 
  workflow_dispatch: ~
  schedule:
    # Every sunday 12:00 UTC, 05:00 PDT
    - cron:  '0 12 * * 0'

jobs:
  release-sync:
    runs-on: ubuntu-latest
    steps:
    # From https://stackoverflow.com/a/61919791
    - id: get_release
      run: | 
        version=`curl --silent "https://api.github.com/repos/clj-kondo/clj-kondo/releases/latest | jq -r .tag_name"`
        echo "::set-output name=releaseTag::$version"
    - run: echo "${{steps.get_release.outputs.releaseTag}}"