name: Release sync

on: 
  workflow_dispatch: ~
  schedule:
    # Every sunday 12:00 UTC, 05:00 PDT
    - cron:  '0 12 * * 0'

jobs:
  release-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          TAG=`curl --silent "https://api.github.com/repos/clj-kondo/clj-kondo/releases/latest" | jq -r .tag_name`
          TAG_WITHOUT_V="${TAG:1}"
          VERSION_STRING=`cat package.json | jq -r '."version-string"'`
          if [ "$VERSION_STRING" != "$TAG_WITHOUT_V" ]; then
            echo "Found new version" $tag_without_v
          fi
