name: Release sync

on: 
  workflow_dispatch: ~
  schedule:
    # Every sunday 12:00 UTC, 05:00 PDT
    - cron:  '0 12 * * 0'

jobs:
  release-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          TAG=`curl --silent "https://api.github.com/repos/clj-kondo/clj-kondo/releases/latest" | jq -r .tag_name`
          NEW_VERSION_STRING="${TAG:1}"
          OLD_VERSION_STRING=`cat package.json | jq -r '."version-string"'`
          if [ "$OLD_VERSION_STRING" != "$NEW_VERSION_STRING" ]; then
            echo "Found new version" $NEW_VERSION_STRING
            sed -i'.bak' -e 's/'$OLD_VERSION_STRING'/'$NEW_VERSION_STRING'/g' package.json
            cat package.json
          else
            echo "No new version found"
          fi
